/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check API and database availability */
        get: operations["health_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List active products */
        get: operations["products_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get an active product by slug */
        get: operations["products_getBySlug"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/articles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List published articles */
        get: operations["articles_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/articles/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a published article by slug */
        get: operations["articles_getBySlug"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the current guest Cart */
        get: operations["cart_getCurrent"];
        put?: never;
        /** Bootstrap the current guest Cart */
        post: operations["cart_bootstrap"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cart/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add a Product Variant to the current Cart */
        post: operations["cart_addItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cart/items/{itemId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a current Cart Item */
        delete: operations["cart_removeItem"];
        options?: never;
        head?: never;
        /** Update a current Cart Item quantity */
        patch: operations["cart_updateItem"];
        trace?: never;
    };
    "/api/v1/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create an awaiting-payment Order from the current Cart */
        post: operations["orders_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/{orderId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a guest-owned Order */
        get: operations["orders_getById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/{orderId}/payment-attempts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a retry Payment Attempt for an Order */
        post: operations["payments_createAttempt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/fake-payments/{paymentAttemptId}/outcome": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Simulate a fake payment outcome */
        post: operations["fakePayments_submitOutcome"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/webhooks/fake-payment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Receive a signed fake payment webhook */
        post: operations["fakePayments_receiveWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ProblemDetailsDto: {
            /**
             * Format: uri
             * @example urn:mini-e-commerce:problem:VALIDATION_FAILED
             */
            type: string;
            /** @example Validation failed */
            title: string;
            /** @example 422 */
            status: number;
            /**
             * @example VALIDATION_FAILED
             * @enum {string}
             */
            code: "MALFORMED_REQUEST" | "GUEST_SESSION_REQUIRED" | "PRODUCT_NOT_FOUND" | "ARTICLE_NOT_FOUND" | "CART_ITEM_NOT_FOUND" | "ORDER_NOT_FOUND" | "CHECKOUT_CART_CHANGED" | "INSUFFICIENT_STOCK" | "IDEMPOTENCY_KEY_REUSED" | "INVALID_ORDER_TRANSITION" | "CART_VERSION_MISMATCH" | "VALIDATION_FAILED" | "PRECONDITION_REQUIRED" | "PAYMENT_GATEWAY_UNAVAILABLE" | "INTERNAL_ERROR";
            /** @example Request validation failed. */
            detail: string;
            /** @example 3fa85f64-5717-4562-b3fc-2c963f66afa6 */
            requestId: string;
            errors?: {
                [key: string]: string[];
            };
            currentCart?: {
                [key: string]: unknown;
            };
            order?: {
                [key: string]: unknown;
            };
            paymentAttempt?: {
                [key: string]: unknown;
            };
        };
        HealthResponseDto: {
            /**
             * @example healthy
             * @enum {string}
             */
            status: "healthy" | "unavailable";
            /**
             * @example available
             * @enum {string}
             */
            database: "available" | "unavailable";
        };
        MoneyDto: {
            /** @example 85000 */
            amount: number;
            /**
             * @example IDR
             * @enum {string}
             */
            currency: "IDR";
        };
        PriceRangeDto: {
            /**
             * @example {
             *       "amount": 85000,
             *       "currency": "IDR"
             *     }
             */
            min: components["schemas"]["MoneyDto"];
            /**
             * @example {
             *       "amount": 155000,
             *       "currency": "IDR"
             *     }
             */
            max: components["schemas"]["MoneyDto"];
        };
        ProductVariantDto: {
            /**
             * Format: uuid
             * @example 20000000-0000-4000-8000-000000000001
             */
            id: string;
            /** @example 250 g */
            optionLabel: string;
            /**
             * @example {
             *       "amount": 85000,
             *       "currency": "IDR"
             *     }
             */
            price: components["schemas"]["MoneyDto"];
            /** @example 12 */
            availableQuantity: number;
        };
        ProductSummaryDto: {
            /**
             * Format: uuid
             * @example 10000000-0000-4000-8000-000000000001
             */
            id: string;
            /** @example kopi-arabika-gayo */
            slug: string;
            /** @example Kopi Arabika Gayo */
            name: string;
            /** @example /images/products/kopi-arabika-gayo.webp */
            thumbnail: string;
            /**
             * @example {
             *       "min": {
             *         "amount": 85000,
             *         "currency": "IDR"
             *       },
             *       "max": {
             *         "amount": 155000,
             *         "currency": "IDR"
             *       }
             *     }
             */
            priceRange: components["schemas"]["PriceRangeDto"] | null;
            /**
             * @example IN_STOCK
             * @enum {string}
             */
            availability: "IN_STOCK" | "LOW_STOCK" | "OUT_OF_STOCK";
        };
        ProductDetailDto: {
            /**
             * Format: uuid
             * @example 10000000-0000-4000-8000-000000000001
             */
            id: string;
            /** @example kopi-arabika-gayo */
            slug: string;
            /** @example Kopi Arabika Gayo */
            name: string;
            /** @example /images/products/kopi-arabika-gayo.webp */
            thumbnail: string;
            /**
             * @example {
             *       "min": {
             *         "amount": 85000,
             *         "currency": "IDR"
             *       },
             *       "max": {
             *         "amount": 155000,
             *         "currency": "IDR"
             *       }
             *     }
             */
            priceRange: components["schemas"]["PriceRangeDto"] | null;
            /**
             * @example IN_STOCK
             * @enum {string}
             */
            availability: "IN_STOCK" | "LOW_STOCK" | "OUT_OF_STOCK";
            /** @example Biji kopi panggang medium untuk seduhan harian. */
            description: string;
            /**
             * @example [
             *       "/images/products/kopi-arabika-gayo.webp"
             *     ]
             */
            images: string[];
            variants: components["schemas"]["ProductVariantDto"][];
        };
        PageInfoDto: {
            /** @example 1 */
            page: number;
            /** @example 20 */
            pageSize: number;
            /** @example 3 */
            totalItems: number;
            /** @example 1 */
            totalPages: number;
        };
        ProductCollectionDto: {
            items: components["schemas"]["ProductSummaryDto"][];
            pageInfo: components["schemas"]["PageInfoDto"];
        };
        ArticleSummaryDto: {
            /**
             * Format: uuid
             * @example 30000000-0000-4000-8000-000000000001
             */
            id: string;
            /** @example panduan-menyeduh-kopi */
            slug: string;
            /**
             * @example PRODUCT
             * @enum {string}
             */
            type: "PRODUCT" | "NEWS" | "OTHER";
            /** @example Panduan Menyeduh Kopi di Rumah */
            title: string;
            /** @example Beberapa langkah sederhana untuk memulai seduhan kopi. */
            excerpt: string;
            /** @example /images/articles/panduan-menyeduh-kopi.webp */
            coverImage: string;
            /**
             * Format: date-time
             * @example 2025-01-10T00:00:00.000Z
             */
            publishedAt: string;
        };
        ArticleDetailDto: {
            /**
             * Format: uuid
             * @example 30000000-0000-4000-8000-000000000001
             */
            id: string;
            /** @example panduan-menyeduh-kopi */
            slug: string;
            /**
             * @example PRODUCT
             * @enum {string}
             */
            type: "PRODUCT" | "NEWS" | "OTHER";
            /** @example Panduan Menyeduh Kopi di Rumah */
            title: string;
            /** @example Beberapa langkah sederhana untuk memulai seduhan kopi. */
            excerpt: string;
            /** @example /images/articles/panduan-menyeduh-kopi.webp */
            coverImage: string;
            /**
             * Format: date-time
             * @example 2025-01-10T00:00:00.000Z
             */
            publishedAt: string;
            /** @example <p>Gunakan air bersih dan takaran kopi yang konsisten.</p> */
            contentHtml: string;
        };
        ArticleCollectionDto: {
            items: components["schemas"]["ArticleSummaryDto"][];
            pageInfo: components["schemas"]["PageInfoDto"];
        };
        CartItemDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            productVariantId: string;
            /** Format: uuid */
            productId: string;
            /** @example kopi-arabika-gayo */
            productSlug: string;
            /** @example Kopi Arabika Gayo */
            productName: string;
            /** @example /images/products/kopi-arabika-gayo.webp */
            thumbnail: string;
            /** @example 250 g */
            optionLabel: string;
            /** @example 2 */
            quantity: number;
            /**
             * @example {
             *       "amount": 85000,
             *       "currency": "IDR"
             *     }
             */
            unitPrice: components["schemas"]["MoneyDto"];
            /**
             * @example {
             *       "amount": 170000,
             *       "currency": "IDR"
             *     }
             */
            lineTotal: components["schemas"]["MoneyDto"];
            /** @example 12 */
            availableQuantity: number;
            /** @example true */
            isAvailable: boolean;
        };
        CartDto: {
            /** Format: uuid */
            id: string;
            /** @example 4 */
            version: number;
            items: components["schemas"]["CartItemDto"][];
            /**
             * @example {
             *       "amount": 170000,
             *       "currency": "IDR"
             *     }
             */
            subtotal: components["schemas"]["MoneyDto"];
        };
        CheckoutCustomerDto: {
            /** @example Ada Lovelace */
            name: string;
            /**
             * Format: email
             * @example ada@example.test
             */
            email: string;
        };
        ShippingAddressDto: {
            /** @example Jl. Contoh 1 */
            line1: string;
            /** @example Jakarta */
            city: string;
            /** @example 10110 */
            postalCode: string;
            /**
             * @example ID
             * @enum {string}
             */
            countryCode: "ID";
        };
        OrderItemDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            productVariantId: string;
            /** @example KOPI-GAYO-250G */
            sku: string;
            /** @example Kopi Arabika Gayo */
            name: string;
            /** @example 250 g */
            optionLabel: string;
            /**
             * @example {
             *       "amount": 85000,
             *       "currency": "IDR"
             *     }
             */
            unitPrice: components["schemas"]["MoneyDto"];
            /** @example 2 */
            quantity: number;
            /**
             * @example {
             *       "amount": 170000,
             *       "currency": "IDR"
             *     }
             */
            lineTotal: components["schemas"]["MoneyDto"];
        };
        PaymentAttemptDto: {
            /** Format: uuid */
            id: string;
            /**
             * @example PENDING
             * @enum {string}
             */
            status: "PENDING" | "SUCCEEDED" | "FAILED" | "EXPIRED";
            /** @example provider-reference */
            providerReference: string;
            /**
             * @example {
             *       "amount": 170000,
             *       "currency": "IDR"
             *     }
             */
            amount: components["schemas"]["MoneyDto"];
            /** Format: date-time */
            expiresAt: string;
            /** Format: date-time */
            createdAt: string;
        };
        OrderDto: {
            /** Format: uuid */
            id: string;
            /**
             * @example AWAITING_PAYMENT
             * @enum {string}
             */
            status: "AWAITING_PAYMENT" | "PAID" | "EXPIRED";
            /** @example Ada Lovelace */
            customerName: string;
            /**
             * Format: email
             * @example ada@example.test
             */
            customerEmail: string;
            shippingAddress: components["schemas"]["ShippingAddressDto"];
            /**
             * @example REGULAR
             * @enum {string}
             */
            shippingMethod: "REGULAR";
            /**
             * @example {
             *       "amount": 170000,
             *       "currency": "IDR"
             *     }
             */
            subtotal: components["schemas"]["MoneyDto"];
            /**
             * @example {
             *       "amount": 0,
             *       "currency": "IDR"
             *     }
             */
            shippingFee: components["schemas"]["MoneyDto"];
            /**
             * @example {
             *       "amount": 170000,
             *       "currency": "IDR"
             *     }
             */
            grandTotal: components["schemas"]["MoneyDto"];
            /** Format: date-time */
            expiresAt: string;
            /** Format: date-time */
            createdAt: string;
            items: components["schemas"]["OrderItemDto"][];
        };
        OrderWithInitialPaymentAttemptDto: {
            /** Format: uuid */
            id: string;
            /**
             * @example AWAITING_PAYMENT
             * @enum {string}
             */
            status: "AWAITING_PAYMENT" | "PAID" | "EXPIRED";
            /** @example Ada Lovelace */
            customerName: string;
            /**
             * Format: email
             * @example ada@example.test
             */
            customerEmail: string;
            shippingAddress: components["schemas"]["ShippingAddressDto"];
            /**
             * @example REGULAR
             * @enum {string}
             */
            shippingMethod: "REGULAR";
            /**
             * @example {
             *       "amount": 170000,
             *       "currency": "IDR"
             *     }
             */
            subtotal: components["schemas"]["MoneyDto"];
            /**
             * @example {
             *       "amount": 0,
             *       "currency": "IDR"
             *     }
             */
            shippingFee: components["schemas"]["MoneyDto"];
            /**
             * @example {
             *       "amount": 170000,
             *       "currency": "IDR"
             *     }
             */
            grandTotal: components["schemas"]["MoneyDto"];
            /** Format: date-time */
            expiresAt: string;
            /** Format: date-time */
            createdAt: string;
            items: components["schemas"]["OrderItemDto"][];
            paymentAttempt: components["schemas"]["PaymentAttemptDto"];
        };
        FakePaymentOutcomeDto: {
            /**
             * @example SUCCEEDED
             * @enum {string}
             */
            outcome: "SUCCEEDED" | "FAILED" | "PENDING";
        };
        FakePaymentWebhookDto: {
            /**
             * @example PAYMENT_SUCCEEDED
             * @enum {string}
             */
            eventType: "PAYMENT_SUCCEEDED" | "PAYMENT_FAILED";
            /** Format: uuid */
            paymentAttemptId: string;
            /** @example provider-reference */
            providerReference: string;
            /** @example 170000 */
            amount: number;
            /**
             * @example IDR
             * @enum {string}
             */
            currency: "IDR";
        };
        WebhookAcknowledgementDto: {
            /** @example true */
            acknowledged: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional safe request ID to propagate. */
                "X-Request-Id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    /** @description Request ID propagated by the API. */
                    "X-Request-Id"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponseDto"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description The API is running but the database is unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponseDto"];
                };
            };
        };
    };
    products_list: {
        parameters: {
            query?: {
                pageSize?: number;
                page?: number;
                sort?: "newest" | "price_asc" | "price_desc";
                /** @description Exact product category filter. */
                category?: string;
                /** @description Case-insensitive search across product name and description. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    /** @description Product data is never cached. */
                    "Cache-Control"?: string;
                    /** @description Request ID propagated by the API. */
                    "X-Request-Id"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductCollectionDto"];
                };
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    products_getBySlug: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    /** @description Product data is never cached. */
                    "Cache-Control"?: string;
                    /** @description Request ID propagated by the API. */
                    "X-Request-Id"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductDetailDto"];
                };
            };
            /** @description Product was not found or is inactive. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    articles_list: {
        parameters: {
            query?: {
                pageSize?: number;
                page?: number;
                type?: "product" | "news" | "other";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    /** @description Published article cache policy. */
                    "Cache-Control"?: string;
                    /** @description Request ID propagated by the API. */
                    "X-Request-Id"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticleCollectionDto"];
                };
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    articles_getBySlug: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    /** @description Published article cache policy. */
                    "Cache-Control"?: string;
                    /** @description Request ID propagated by the API. */
                    "X-Request-Id"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticleDetailDto"];
                };
            };
            /** @description Article was not found or is unpublished. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    cart_getCurrent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    /** @description Quoted Cart version. */
                    ETag?: string;
                    /** @description Cart responses are never cached. */
                    "Cache-Control"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CartDto"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    cart_bootstrap: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    /** @description Quoted Cart version. */
                    ETag?: string;
                    /** @description Cart responses are never cached. */
                    "Cache-Control"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CartDto"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    cart_addItem: {
        parameters: {
            query?: never;
            header: {
                /** @description Quoted Cart version, for example "1". */
                "If-Match": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    /** @description Quoted Cart version. */
                    ETag?: string;
                    /** @description Cart responses are never cached. */
                    "Cache-Control"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CartDto"];
                };
            };
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            428: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    cart_removeItem: {
        parameters: {
            query?: never;
            header: {
                /** @description Quoted Cart version, for example "1". */
                "If-Match": string;
            };
            path: {
                itemId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    /** @description Quoted Cart version. */
                    ETag?: string;
                    /** @description Cart responses are never cached. */
                    "Cache-Control"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CartDto"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            428: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    cart_updateItem: {
        parameters: {
            query?: never;
            header: {
                /** @description Quoted Cart version, for example "1". */
                "If-Match": string;
            };
            path: {
                itemId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    /** @description Quoted Cart version. */
                    ETag?: string;
                    /** @description Cart responses are never cached. */
                    "Cache-Control"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CartDto"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            428: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    orders_create: {
        parameters: {
            query?: never;
            header: {
                /** @description Printable ASCII key, 16 to 128 characters. */
                "Idempotency-Key": string;
                /** @description Quoted Cart version, for example "2". */
                "If-Match": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderWithInitialPaymentAttemptDto"];
                };
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            428: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    orders_getById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    "Cache-Control"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderDto"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    payments_createAttempt: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentAttemptDto"];
                };
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    fakePayments_submitOutcome: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                paymentAttemptId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentAttemptDto"];
                };
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    fakePayments_receiveWebhook: {
        parameters: {
            query?: never;
            header: {
                "X-Fake-Signature": string;
                "X-Fake-Timestamp": string;
                "X-Fake-Event-Id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FakePaymentWebhookDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookAcknowledgementDto"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
}
